### ISSUE TITLE
Latest "Just Report It" does not Delete or Move to Trash after sending message to Spamcop.

### ISSUE THREAD

**Issue by djringjr** [justreportit/thunderbird#62] opened 2024-04-05 15:19 UTC
Latest "Just Report It" does not Delete or Move to Trash after sending message to Spamcop.

.

**Comment by nicprov** [comment] 2024-08-02 19:56
@djringjr This was caused by an update to Thunderbird requiring a new permission to delete files. This has been fixed in the latest release.

**Closed by nicprov** 2024-08-02 19:56 UTC
